.github/workflows/mirror.yml

I've added the chocolatine project for link this repo to the epitech repo.

feat: chocolatine project

---

express-backend/.gitignore
express-backend/index.ts
express-backend/package-lock.json
express-backend/package.json
express-backend/tsconfig.json

Feature the express-backend/ folder featuring express with typescript for the server, which will later connect to postgresql if this choice doesn't change.

feat: express-backend/ folder with backend initialized

---

angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/navbar/navbar.component.spec.ts
angular-frontend/src/app/navbar/navbar.component.ts

I created the navbar for the application.
>[!IMPORTANT]
> We must add the different links for buttons
> Trigger the click on navbar menu button when phone size

feat: navbar html and scss

---

angular-frontend/package-lock.json
angular-frontend/src/app/app.module.ts
angular-frontend/src/app/client-profile/client-profile.component.html
angular-frontend/src/app/client-profile/client-profile.component.scss
angular-frontend/src/app/client-profile/client-profile.component.spec.ts
angular-frontend/src/app/client-profile/client-profile.component.ts

I created a simple work in progress html page for the client profile.

Create the client profile page

---

angular-frontend/src/app/app-routing.module.ts
angular-frontend/src/app/app.module.ts

I enable routing for pages.
Now in the search bar, in the navigator, we can access to all pages of the route list.

Handle routing task

---

express-backend/index.ts
express-backend/routes/tips.ts

I'd initialized all the endpoint for tips, included the creation, read, update and delete (CRUD) !

feat: add endpoint for tips page

---

express-backend/index.ts
express-backend/prisma/migrations/20240903125317_add_models/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts
express-backend/routes/tips.ts

I'd initialized all the endpoint for customer, included the creation, read, update and delete (CRUD) !

feat: add endpoint for customer

---

express-backend/index.ts
express-backend/prisma/migrations/20240903140705_modified_default_value/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts
express-backend/routes/employees.ts

I'd initialized all the endpoint for employees, included the creation, read, update and delete (CRUD) !

feat: add routes about employees

---

express-backend/index.ts
express-backend/package-lock.json
express-backend/package.json
express-backend/prisma/migrations/20240903201749_delete_default_value/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts
express-backend/routes/employees.ts
express-backend/routes/events.ts

I'd initialized all the endpoints for events, included the creation, read, update and delete (CRUD) !

feat: add endpoint for events

---

express-backend/index.ts
express-backend/routes/encounters.ts

I'd initialized all the endpoint for encounters, included the creation, read, update and delete (CRUD) !

feat: add endpoint for encounters

---

angular-frontend/src/app/pages/client-profile/client-profile.component.html
angular-frontend/src/app/pages/client-profile/client-profile.component.ts

I displayed the customers' information based on the API.

feat: display customers information based on the API

---

angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/navbar/navbar.component.scss
angular-frontend/src/app/navbar/navbar.component.ts

feat: new navbar using bulma & responsive

---

angular-frontend/src/app/app-routing.module.ts
angular-frontend/src/app/app.module.ts
angular-frontend/src/app/pages/home/component/charts/charts.component.spec.ts
angular-frontend/src/app/pages/home/component/charts/charts.component.ts
angular-frontend/src/app/pages/home/home.component.html
angular-frontend/src/app/pages/home/home.component.scss
angular-frontend/src/app/pages/home/home.component.ts

I've added a static home page, a dashboard.
>[!IMPORTANT]
> This page is fixed and is not linked to the database.

feat: add a static home page (dashboard)

---

express-backend/prisma/migrations/20240904135525_coach_for_customer/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts
express-backend/routes/employees.ts

Successfully added the new endpoint /employees/customers/:id

link clients to employees

---

angular-frontend/src/app/app-routing.module.ts

I've fix the navbar in the statistics and wardrobe pages, I add the guards for these two pages.

fix: added the guards in statistics and wardrobe page

---

angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/navbar/navbar.component.scss

I ugrade the navbar look, and I linked the buttons to pages.

Link navbar buttons with pages

---

express-backend/prisma/migrations/20240904160503_/migration.sql
express-backend/prisma/migrations/20240904160756_last_login/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/login.ts

Frontend can now get last_login from employees

feat: added last_login to db and api

---

express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchClothes.ts
express-backend/prisma/fetchData/fetchCustomers.ts
express-backend/prisma/fetchData/fetchTips.ts
express-backend/prisma/migrations/20240904145800_add/migration.sql
express-backend/prisma/migrations/20240904152626_add/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts

I'd added in the schema of customer the list of clothe that have the customer. And I added in the scrypt the fetch of customer.

feat: add clothe for each customer and scypt to fetch data

---

angular-frontend/src/app/app-routing.module.ts
angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/pages/coaches/coaches.component.html
angular-frontend/src/app/pages/coaches/coaches.component.scss

I created the aesthetic of the coaches page.

Create the coach page

---

angular-frontend/src/app/pages/coaches/coaches.component.html
angular-frontend/src/app/pages/coaches/coaches.component.ts
angular-frontend/src/app/service/customers/customers.service.ts
angular-frontend/src/app/service/employees/employees.service.ts

I linked the API with the coaches page.
When we assign clients to coaches, we can save changes and a request is sent to the API to update clients

Link the coaches page with database

---

express-backend/index.ts
express-backend/package-lock.json
express-backend/package.json
express-backend/prisma/migrations/20240904213400_customer_id_paymenthistory/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/paymentHistory.ts

Successfully added /paymenthistory with all the crud and /customer/:id to send back the user's payment history

feature paymenthistory router + secure all routes with middleware isloggedin

---

express-backend/middlewares/isLoggedIn.ts
express-backend/routes/employees.ts

Endpoint successfully added, allowing many features from the client.

Feature /employees/me

---

express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchEmployees.ts
express-backend/routes/compatibility.ts
express-backend/routes/employees.ts

Hello,
I'd added the fetch of employees data !

feat: fetch employees data

---

angular-frontend/src/app/pages/astrological-compatibility/astrological-compatibility.component.html
angular-frontend/src/app/pages/astrological-compatibility/astrological-compatibility.component.scss
angular-frontend/src/app/pages/astrological-compatibility/astrological-compatibility.component.ts
angular-frontend/src/app/service/compatibility/compatibility.service.spec.ts
angular-frontend/src/app/service/compatibility/compatibility.service.ts
angular-frontend/src/app/service/employees/employees.service.ts

I linked the API data with the astrological compatibility page.

Link astrological compatibility page with database

---

express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchCustomers.ts
express-backend/prisma/migrations/20240905111430_add_image_url_customer/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts

I'd add the image_url of the customer in the schema of prisma and in the fetch of APi data !

feat: add image_url of customer

---

angular-frontend/src/app/pages/wardrobe/wardrobe.component.html
angular-frontend/src/app/pages/wardrobe/wardrobe.component.ts

I've added a backup image in wardrobe page.

feat: add backup image in wardrobe page

---

express-backend/routes/login.ts

fix: login works with already existing user & empty pwd

---

express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchCustomers.ts
express-backend/prisma/fetchData/fetchPaymentHistory.ts
express-backend/prisma/migrations/20240905201505_add_payment_history/migration.sql
express-backend/prisma/migrations/20240905204743_add_payment_history_amout_float/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts

I've fetch all payment history to the schema and create in the schema of customer a tab of index of payment.

feat: add payment to customer

---

angular-frontend/src/app/pages/wardrobe/wardrobe.component.html

I've fixde the mobile format for wardrobe page.
> [!CAUTION]
> The wardrobe menu is still on the left

fix: responsive for mobile format in wardrobe page

---

angular-frontend/src/app/pages/statistics/statistics.component.html
angular-frontend/src/app/pages/statistics/statistics.component.scss

I've upgrade the responsive format for statistics page in mobile format.

feat: upgrade the responsive of statistics in mobile format

---

angular-frontend/src/app/pages/login/login.component.html
angular-frontend/src/app/pages/login/login.component.scss

I've create responsive format of login page.

fix: responsive format of login page

---

express-backend/index.ts
express-backend/legacy/accountsLegacy.ts
express-backend/prisma/fetchData/fetchClothes.ts
express-backend/prisma/fetchData/fetchCustomers.ts
express-backend/prisma/fetchData/fetchEmployees.ts
express-backend/prisma/migrations/20240909091835_postgres_bytea_imge_saves/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/assets.ts

Feature the images now stored in database as bytes (bytea) in postgres. Allows us to be more flexible for upload and production of the app.

Store images in db

---

express-backend/middlewares/isLoggedIn.ts
express-backend/middlewares/isManager.ts
express-backend/prisma/fetchData/fetchClothes.ts
express-backend/routes/customers.ts
express-backend/routes/employees.ts
express-backend/routes/encounters.ts
express-backend/routes/events.ts
express-backend/routes/paymentHistory.ts

I've create middleware for authentification to improve security.
Now the coach can't acces to every data.

Create middleware for auth

---

express-backend/prisma/fetchData/fetchClothes.ts
express-backend/routes/clothes.ts

I've fix the fetch of clothes.

fix: fetch of clothes

---

angular-frontend/src/app/pages/wardrobe/wardrobe.component.ts
angular-frontend/src/app/service/auth/auth.service.ts

I've fix the customers request in wardrobe page.

fix(wardrobe page): request of customers

---

angular-frontend/src/app/app-routing.module.ts
angular-frontend/src/app/app.module.ts
angular-frontend/src/app/pages/coaches/coaches.component.html
angular-frontend/src/app/pages/coaches/coaches.component.ts
angular-frontend/src/app/pages/delete-employee/delete-employee.component.html
angular-frontend/src/app/pages/delete-employee/delete-employee.component.scss
angular-frontend/src/app/pages/delete-employee/delete-employee.component.spec.ts
angular-frontend/src/app/pages/delete-employee/delete-employee.component.ts

I've added the deleting employee button and page.

feat: add delete employee

---

express-backend/index.ts
express-backend/package-lock.json
express-backend/package.json
express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchClothes.ts

Add system of cron in the index.ts and I added the stop of the cron when the index.ts is stopped. I'd also optimize the fetch of clothes.

Add system of cron and optimise fetch of clothe

---

angular-frontend/src/app/app.component.html
angular-frontend/src/app/app.component.scss
angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/navbar/navbar.component.scss
angular-frontend/src/app/navbar/navbar.component.ts

refactor: navbar using Bootstrap

---

express-backend/routes/customers.ts

I've upgrade the route to get now directly the url and the type more faster than before !

Add route to get customer clothe by id

---

angular-frontend/src/app/pages/tips/tips.component.html
angular-frontend/src/app/pages/tips/tips.component.scss
angular-frontend/src/assets/i18n/en.json
angular-frontend/src/assets/i18n/es.json
angular-frontend/src/assets/i18n/fr.json
angular-frontend/src/assets/i18n/zh.json
express-backend/package-lock.json
express-backend/package.json

Followed the mockup. Almost exactly the same. expected the active state of the tip accordion and the header.
expected : 
current render:

Refactor for new mockup tips

---

angular-frontend/src/app/navbar/navbar.component.html
angular-frontend/src/app/navbar/navbar.component.ts
angular-frontend/src/assets/i18n/en.json

feat: translate new nav transloco

---

express-backend/prisma/migrations/20240911122633_add_coach_favorite/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts

I'd added a schema to customer data base, and I added in Put route the upgrade !

feat: add coach favorite to schema customer

---

express-backend/routes/employees.ts

I'd added the number of customer per coach when getting all employees !

feat: add nomber of customer in employees

---

express-backend/index.ts
express-backend/routes/customers.ts
express-backend/routes/paymentHistory.ts

I'd added 2 route;
The first one is about to know the total of payment.
The second is about to know the total of paylent of a customer.

feat: add 2 routes for payment

---

express-backend/routes/customers.ts

I'd added the last payment method to the list of customer !

feat: add last payment method in list of customer

---

express-backend/index.ts
express-backend/routes/dashboard.ts

I'd added route for get data dashboard !

feat: add route to get data for dashboard

---

express-backend/routes/dashboard.ts

I'd added a route to get a list of date of a period with the number of event during each day !

feat: add route to get event at each day

---

express-backend/package-lock.json
express-backend/package.json
express-backend/prisma/fetchData/fetchAndStoreData.ts
express-backend/prisma/fetchData/fetchCustomers.ts
express-backend/prisma/migrations/20240912134528_add_phone_number_and_address_to_customer/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/customers.ts
express-backend/routes/dashboard.ts
express-backend/routes/themes.ts

Added adress and phone number for customer in db !

feat: add in db the adress and phone number for customer
